### ISSUE TITLE
ingressClassName spec is breaking ingresses on k3s 

### ISSUE THREAD

**Issue by giubacc** [aquarist-labs/s3gw-charts#9]
In ingress manifests, having 
```
spec:
  ingressClassName: ingress-traefik
```
is breaking ingresses on k3s.
I took a look at traefik helm chart, it seems to me that by default ingressClass is disabled:

```
# Use ingressClass. Ignored if Traefik version < 2.3 / kubernetes < 1.18.x
ingressClass:
  # true is not unit-testable yet, pending https://github.com/rancher/helm-unittest/pull/12
  enabled: false
  isDefaultClass: false
  # Use to force a networking.k8s.io API Version for certain CI/CD applications. E.g. "v1beta1"
  fallbackApiVersion: ""
``` 

@m-ildefons  Is it possible that you have some dirty traefik deployment on your env?
Because we are mainly targeting k3s, do you think could it be reasonable to remove the `ingressClassName` spec from s3gw chart?
